### ISSUE TITLE
There are duplicates of all the original people AND faces are missing from all new people.

### ISSUE THREAD

**Issue by jasonrohrer** [jasonrohrer/AnotherPlanetData#12]
I see that there are new "swaying" versions of all the original people.

However, the old people are still present.  This means that people have a chance to spawn as either swaying or non-swaying.  Maybe this is intentional?  If not, the old non-swaying people should probably be removed.

Regardless of whether the duplicates should stay or not, NONE of the new people have faces that have been generated and saved in the git content repo.  This means they're also missing from the family tree.

I'm pretty sure the BAT script for content leader is doing this correctly....

I'm guessing the problem is simply that the new people were imported using a mod by the content leader, and then the content leader never touched them after that.

It's a bit of a pain, but you do need to SAVE each one at least once, in your own editor, to generate the faces images locally.  After that, they should get committed.

Note that currently, saving them will update the authorship hash for these people, which you may not want to do.  You can probably cherry-pick what you commit with git, and "git checkout" inside "objects" to restore the old hashes before committing.  And then just commit the new faces.

(I will be fixing this authorship-overwriting thing soon.)

There's also a chance that something else isn't working, and that you HAVE generated the faces on your end.... in that case, maybe there's something wrong with the BAT script that copies changes over into the local git repo (if you're still using that script).

**Comment by jasonrohrer** [comment]
Note that by "new people," I mean the swaying people, and also the two new female characters---they don't have faces generated either.

**Comment by MarkLindsay** [comment]
@DopiePanda, did I notice some recent changes to the characters? Has this issue been resolved?

**Comment by DopiePanda** [comment]
> @DopiePanda, did I notice some recent changes to the characters? Has this issue been resolved?

Yes, this issue was fixed with the last patch! :)
