### ISSUE TITLE
Vote by email hash instead of email.

### ISSUE THREAD

**Issue by lorocyproca** [jasonrohrer/AnotherPlanetData#2]
The player hash exists to protect the email in the first place, and many members of the community are already accustomed with finding their own or others' player hash to check curse history, which is supported by the oholcurse site. This allows people to vote for players for content leader based on a verifiable link between player and account, without compromising the sensitivity of their steam email. 

If this is already how it works, please disregard this issue, I just heard that you planned on having people share their emails as part of the voting process.

**Comment by jasonrohrer** [comment]
This was fixed so that people vote by github account name instead.
